package ndhieu.thesis.activiti.businessprocess.use.testcases;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

public class CreateRBACPolicyConsistencyVerifyTC {

	public static void main(String[] args) throws IOException {

		File file = new File("SecurityPolicySpecificationConsistencyVerifyTC.soil");

		if (!file.exists()) {
			file.createNewFile();
		}

		FileWriter fw = new FileWriter(file);
		BufferedWriter bw = new BufferedWriter(fw);
		PrintWriter pw = new PrintWriter(bw);

		pw.println("-- Script generated by USE 5.1.0");
		pw.println();

		pw.println("!new Role('r1')");
		pw.println("!r1.name := 'HeadOfDepartment'");
		pw.println("!r1.maxUsers := 2");
		pw.println("!r1.maxJuniors := 0");
		pw.println("!r1.maxSeniors := 0");
		pw.println("!new Role('r2')");
		pw.println("!r2.name := 'AssistantOfAcademicAffairsOffice'");
		pw.println("!r2.maxUsers := 1");
		pw.println("!r2.maxJuniors := 0");
		pw.println("!r2.maxSeniors := 2");
		pw.println("!new Role('r3')");
		pw.println("!r3.name := 'StaffOfPlanningFinanceOffice'");
		pw.println("!r3.maxUsers := 2");
		pw.println("!r3.maxJuniors := 1");
		pw.println("!r3.maxSeniors := 1");
		pw.println("!new Role('r4')");
		pw.println("!r4.name := 'Director'");
		pw.println("!r4.maxUsers := 1");
		pw.println("!r4.maxJuniors := 2");
		pw.println("!r4.maxSeniors := 0");

		pw.println("!new User('u1')");
		pw.println("!u1.name := 'Thuan'");
		pw.println("!u1.maxRoles := 1");
		pw.println("!u1.rolesHierarchy := false");
		pw.println("!new User('u2')");
		pw.println("!u2.name := 'Hanh'");
		pw.println("!u2.maxRoles := 1");
		pw.println("!u2.rolesHierarchy := false");
		pw.println("!new User('u3')");
		pw.println("!u3.name := 'Vinh'");
		pw.println("!u3.maxRoles := 2");
		pw.println("!u3.rolesHierarchy := true");
		pw.println("!new User('u4')");
		pw.println("!u4.name := 'Hieu'");
		pw.println("!u4.maxRoles := 3");
		pw.println("!u4.rolesHierarchy := true");

		pw.println("!new Permission('p11')");
		pw.println("!p11.name := 'ContractReading'");
		pw.println("!p11.maxRoles := 4");
		pw.println("!p11.maxSessions := 6");
		pw.println("!new Permission('p12')");
		pw.println("!p12.name := 'ContractChecking'");
		pw.println("!p12.maxRoles := 1");
		pw.println("!p12.maxSessions := 2");
		pw.println("!new Permission('p21')");
		pw.println("!p21.name := 'ContractReview'");
		pw.println("!p21.maxRoles := 3");
		pw.println("!p21.maxSessions := 4");
		pw.println("!new Permission('p22')");
		pw.println("!p22.name := 'NotificationSending'");
		pw.println("!p22.maxRoles := 3");
		pw.println("!p22.maxSessions := 4");
		pw.println("!new Permission('p3')");
		pw.println("!p3.name := 'ContractValidation'");
		pw.println("!p3.maxRoles := 2");
		pw.println("!p3.maxSessions := 3");
		pw.println("!new Permission('p4')");
		pw.println("!p4.name := 'PaymentApproval'");
		pw.println("!p4.maxRoles := 1");
		pw.println("!p4.maxSessions := 1");

		pw.println("!new Session('s1')");
		pw.println("!s1.name := 'thuanS'");
		pw.println("!new Session('s2')");
		pw.println("!s2.name := 'hanhS'");
		pw.println("!new Session('s3')");
		pw.println("!s3.name := 'vinhS'");
		pw.println("!new Session('s4')");
		pw.println("!s4.name := 'hieuS'");

		pw.println("!insert (u1,r1) into UA");
		pw.println("!insert (p11,r1) into PA");
		pw.println("!insert (p12,r1) into PA");
		pw.println("!insert (u1,s1) into Establishes");
		pw.println("!insert (s1,r1) into Activates");
		pw.println("!insert (p12,p11) into PrerequisitePermissions");

		pw.println("!insert (u2,r2) into UA");
		pw.println("!insert (p21,r2) into PA");
		pw.println("!insert (p22,r2) into PA");
		pw.println("!insert (p11,r2) into PA");
		pw.println("!insert (u2,s2) into Establishes");
		pw.println("!insert (s2,r2) into Activates");
		pw.println("!insert (p21,p11) into PrerequisitePermissions");
		pw.println("!insert (p22,p11) into PrerequisitePermissions");

		pw.println("!insert (u3,r3) into UA");
		pw.println("!insert (p3,r3) into PA");
		pw.println("!insert (p21,r3) into PA");
		pw.println("!insert (p22,r3) into PA");
		pw.println("!insert (p11,r3) into PA");
		pw.println("!insert (u3,s3) into Establishes");
		pw.println("!insert (s3,r3) into Activates");
		pw.println("!insert (p3,p11) into PrerequisitePermissions");
		pw.println("!insert (p3,p21) into PrerequisitePermissions");

		pw.println("!insert (u4,r4) into UA");
		pw.println("!insert (p4,r4) into PA");
		pw.println("!insert (p3,r4) into PA");
		pw.println("!insert (p21,r4) into PA");
		pw.println("!insert (p22,r4) into PA");
		pw.println("!insert (p11,r4) into PA");
		pw.println("!insert (u4,s4) into Establishes");
		pw.println("!insert (s4,r4) into Activates");
		pw.println("!insert (p4,p11) into PrerequisitePermissions");
		pw.println("!insert (p4,p3) into PrerequisitePermissions");
		pw.println("!insert (p4,p21) into PrerequisitePermissions");

		pw.println("!insert (r3,r2) into RH");
		pw.println("!insert (r4,r3) into RH");

		pw.close();
		bw.close();
		fw.close();
	}

}
